# coding: utf-8

"""
    Wire4RestAPI

    Referencia de API. La API de Wire4 está organizada en torno a REST  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from api.lmites_de_montos_api import LmitesDeMontosApi  # noqa: E501
from wire4_client.rest import ApiException


class TestLmitesDeMontosApi(unittest.TestCase):
    """LmitesDeMontosApi unit test stubs"""

    def setUp(self):
        self.api = api.lmites_de_montos_api.LmitesDeMontosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_obtain_configurations_limits(self):
        """Test case for obtain_configurations_limits

        Consulta de configuraciones  # noqa: E501
        """
        pass

    def test_update_configurations(self):
        """Test case for update_configurations

        Actualiza configuraciones por suscripción  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
