# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from wire4_client.api.autorizacin_de_depsitos_api import AutorizacinDeDepsitosApi  # noqa: E501
from wire4_client.rest import ApiException


class TestAutorizacinDeDepsitosApi(unittest.TestCase):
    """AutorizacinDeDepsitosApi unit test stubs"""

    def setUp(self):
        self.api = AutorizacinDeDepsitosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_deposit_auth_configurations(self):
        """Test case for get_deposit_auth_configurations

        Consulta autorización de depósitos  # noqa: E501
        """
        pass

    def test_put_deposit_auth_configurations(self):
        """Test case for put_deposit_auth_configurations

        Habilita / Deshabilita la autorización de depósitos  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
