# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from wire4_client.api.saldo_api import SaldoApi  # noqa: E501
from wire4_client.rest import ApiException


class TestSaldoApi(unittest.TestCase):
    """SaldoApi unit test stubs"""

    def setUp(self):
        self.api = SaldoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_balance_using_get(self):
        """Test case for get_balance_using_get

        Consulta los saldo de una cuenta  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
