# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from wire4_client.models.message_institution import MessageInstitution  # noqa: E501
from wire4_client.rest import ApiException


class TestMessageInstitution(unittest.TestCase):
    """MessageInstitution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageInstitution(self):
        """Test MessageInstitution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wire4_client.models.message_institution.MessageInstitution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
