# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from wire4_client.models.urls_redirect import UrlsRedirect  # noqa: E501
from wire4_client.rest import ApiException


class TestUrlsRedirect(unittest.TestCase):
    """UrlsRedirect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUrlsRedirect(self):
        """Test UrlsRedirect"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wire4_client.models.urls_redirect.UrlsRedirect()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
