# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from wire4_client.models.authorized_beneficiaries_response import AuthorizedBeneficiariesResponse  # noqa: E501
from wire4_client.rest import ApiException


class TestAuthorizedBeneficiariesResponse(unittest.TestCase):
    """AuthorizedBeneficiariesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthorizedBeneficiariesResponse(self):
        """Test AuthorizedBeneficiariesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wire4_client.models.authorized_beneficiaries_response.AuthorizedBeneficiariesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
