# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from wire4_client.api.reporte_de_solicitudes_de_pagos_api import ReporteDeSolicitudesDePagosApi  # noqa: E501
from wire4_client.rest import ApiException


class TestReporteDeSolicitudesDePagosApi(unittest.TestCase):
    """ReporteDeSolicitudesDePagosApi unit test stubs"""

    def setUp(self):
        self.api = ReporteDeSolicitudesDePagosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payment_request_id_report_by_order_id_using_get(self):
        """Test case for payment_request_id_report_by_order_id_using_get

        Consulta de solicitudes de pago por numero de orden.  # noqa: E501
        """
        pass

    def test_payment_request_id_report_using_get(self):
        """Test case for payment_request_id_report_using_get

        Consulta de solicitudes de pago por identificador de petición  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
