# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wire4_client
from wire4_client.api.solicitud_de_pagos_api import SolicitudDePagosApi  # noqa: E501
from wire4_client.rest import ApiException


class TestSolicitudDePagosApi(unittest.TestCase):
    """SolicitudDePagosApi unit test stubs"""

    def setUp(self):
        self.api = SolicitudDePagosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_register_payment_request_using_post(self):
        """Test case for register_payment_request_using_post

        Registro de solicitud de pagos  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
