# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthorizedBeneficiariesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accounts': 'list[AccountReassigned]',
        'request_id': 'str',
        'url': 'str'
    }

    attribute_map = {
        'accounts': 'accounts',
        'request_id': 'request_id',
        'url': 'url'
    }

    def __init__(self, accounts=None, request_id=None, url=None):  # noqa: E501
        """AuthorizedBeneficiariesResponse - a model defined in Swagger"""  # noqa: E501
        self._accounts = None
        self._request_id = None
        self._url = None
        self.discriminator = None
        if accounts is not None:
            self.accounts = accounts
        if request_id is not None:
            self.request_id = request_id
        if url is not None:
            self.url = url

    @property
    def accounts(self):
        """Gets the accounts of this AuthorizedBeneficiariesResponse.  # noqa: E501

        Lista de cuentas obtenidas en estado pendiente de ser autorizadas.  # noqa: E501

        :return: The accounts of this AuthorizedBeneficiariesResponse.  # noqa: E501
        :rtype: list[AccountReassigned]
        """
        return self._accounts

    @accounts.setter
    def accounts(self, accounts):
        """Sets the accounts of this AuthorizedBeneficiariesResponse.

        Lista de cuentas obtenidas en estado pendiente de ser autorizadas.  # noqa: E501

        :param accounts: The accounts of this AuthorizedBeneficiariesResponse.  # noqa: E501
        :type: list[AccountReassigned]
        """

        self._accounts = accounts

    @property
    def request_id(self):
        """Gets the request_id of this AuthorizedBeneficiariesResponse.  # noqa: E501

        Es el identificador público generado para la petición (solicitud).  # noqa: E501

        :return: The request_id of this AuthorizedBeneficiariesResponse.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this AuthorizedBeneficiariesResponse.

        Es el identificador público generado para la petición (solicitud).  # noqa: E501

        :param request_id: The request_id of this AuthorizedBeneficiariesResponse.  # noqa: E501
        :type: str
        """

        self._request_id = request_id

    @property
    def url(self):
        """Gets the url of this AuthorizedBeneficiariesResponse.  # noqa: E501

        Es la dirección URL generada para confirmación de la operación. Es para ingresar al centro de autorización.  # noqa: E501

        :return: The url of this AuthorizedBeneficiariesResponse.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AuthorizedBeneficiariesResponse.

        Es la dirección URL generada para confirmación de la operación. Es para ingresar al centro de autorización.  # noqa: E501

        :param url: The url of this AuthorizedBeneficiariesResponse.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorizedBeneficiariesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorizedBeneficiariesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
