# coding: utf-8

"""
    Wire4RestAPI

    Referencia de la API de Wire4  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DepositantsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'clabe': 'str'
    }

    attribute_map = {
        'clabe': 'clabe'
    }

    def __init__(self, clabe=None):  # noqa: E501
        """DepositantsResponse - a model defined in Swagger"""  # noqa: E501
        self._clabe = None
        self.discriminator = None
        if clabe is not None:
            self.clabe = clabe

    @property
    def clabe(self):
        """Gets the clabe of this DepositantsResponse.  # noqa: E501

        Cuenta CLABE (es de 18 dígitos) del depositante.  # noqa: E501

        :return: The clabe of this DepositantsResponse.  # noqa: E501
        :rtype: str
        """
        return self._clabe

    @clabe.setter
    def clabe(self, clabe):
        """Sets the clabe of this DepositantsResponse.

        Cuenta CLABE (es de 18 dígitos) del depositante.  # noqa: E501

        :param clabe: The clabe of this DepositantsResponse.  # noqa: E501
        :type: str
        """

        self._clabe = clabe

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DepositantsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DepositantsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
